# Numpy

In [2]:
import numpy as np
from numpy import dtype

In [4]:
mt = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(mt)
print(type(mt))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>


In [5]:
mtfloat = np.array([1,2,3], dtype = np.float64)
print(mtfloat)
print(type(mtfloat))

mtint = np.array([1,2,3], dtype = np.int32)
print(mtint)
print(type(mtint))

[1. 2. 3.]
<class 'numpy.ndarray'>
[1 2 3]
<class 'numpy.ndarray'>


In [6]:
mtnew = np.array([1.3, 2.4, -3.5, 4.999999999], dtype = np.float64)
print(mtnew)

mtnewint = mtnew.astype(np.int32)
print(mtnewint)

[ 1.3  2.4 -3.5  5. ]
[ 1  2 -3  4]


In [7]:
mt5 = np.array([1,2,3])
print(mt5)
mt6 = mt5.astype(float)
print(mt6)

[1 2 3]
[1. 2. 3.]


In [8]:
mt7 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(mt7)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [9]:
vazio = np.empty([3,2], dtype = int)
print(vazio)
print("-------")

zeros = np.zeros([4,3])
print(zeros)
print("-------")

um = np.ones([5,7])
print(um)
print("-------")

diagonal = np.eye(5)
print(diagonal)

[[0 0]
 [0 0]
 [0 0]]
-------
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
-------
[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]
-------
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [10]:
ale = np.random.random((5))
print(ale)
print("-------")

ale2 = np.random.randn((5))
print(ale2)
print("-------")

ale3 = (10*np.random.random((3,4)))
print(ale3)

[0.96355451 0.9985946  0.98445548 0.18314074 0.67790368]
-------
[ 1.02584707  0.85580992  0.15275698 -0.58891806 -0.74323688]
-------
[[5.47650852 6.01290908 0.3178844  0.6783666 ]
 [2.22386161 6.4608988  1.80044405 6.07852536]
 [4.46494031 8.11071348 9.4258738  0.74365849]]


In [11]:
gnr = np.random.default_rng(1)
ale5 = gnr.random(3)
print(ale5)

ale6 = gnr.integers(10, size=(3,4))
print(ale6)

[0.51182162 0.9504637  0.14415961]
[[8 9 2 3]
 [8 4 2 8]
 [2 4 6 5]]


In [13]:
j = np.array([11, 11, 12, 13, 14, 11, 15])
j = np.unique(j)
print(j)

[11 12 13 14 15]


In [3]:
k = np.array([[11,22,33], [55,66,77], [88,99,00]])
print(k)
print(k[0][1])
print(k.shape)

[[11 22 33]
 [55 66 77]
 [88 99  0]]
22
(3, 3)


In [4]:
print(k.max())
print(k.min())
print(k.sum())
print(k.mean())
print(k.std())

99
0
451
50.111111111111114
33.24803902135331


In [8]:
k1 = np.array([1, 4, 9, 16, 25, 36])
print(np.sqrt(k1))
print(np.exp(k1))

[1. 2. 3. 4. 5. 6.]
[2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06
 7.20048993e+10 4.31123155e+15]


In [9]:
m = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(m[1])
print("--------")

print(m[0:2])
print("--------")

print(m[1:])
print("--------")

print(m[-3:])

2
--------
[1 2]
--------
[2 3 4 5 6 7 8 9]
--------
[7 8 9]


In [10]:
l = np.array([[1,2],[4,5],[7,8]])
print(l)
print("--------")

l_line_1 = l[0, :]
print(l_line_1)
print("--------")

l_line_2 = l[1, :]
print(l_line_2)
print("--------")

l_line_3 = l[2, :]
print(l_line_3)
print("--------")

l_column_1 = l[: ,0]
print(l_column_1)
print("--------")

l_column_2 = l[: ,1]
print(l_column_2)
print("--------")

[[1 2]
 [4 5]
 [7 8]]
--------
[1 2]
--------
[4 5]
--------
[7 8]
--------
[1 4 7]
--------
[2 5 8]
--------


In [3]:
n = np.array([[1,2], [3,4]])
o = np.array([[1,1], [1,1]])
rest1 = n + o
print(rest1)
print("--------")

rest2 = n * o
print(rest2)
print("--------")

p = np.array([[1,2], [3,4], [5,6]])
q = np.array([[2,1]])
print(p*q)

[[2 3]
 [4 5]]
--------
[[1 2]
 [3 4]]
--------
[[ 2  2]
 [ 6  4]
 [10  6]]


In [4]:
f = np.arange(15).reshape((3, 5))
print(f)
print("--------")
s = f.T
print(s)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
--------
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


In [5]:
r = np.arange(15).reshape((3, 5))
print(r)
print("--------")

s = r.transpose((1,0))
print(s)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
--------
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


In [6]:
v = np.random.randn(4,4)
print(v)

x = (v > 0)
print(x)

z = np.where(x > 0, 1, -1)
print(z)

[[ 0.44521988 -1.13506873  1.06455138  0.41641477]
 [-0.12551529  1.17599101  2.78751312  0.85882242]
 [ 0.03591693  1.61640754  0.70956447 -0.46198867]
 [ 0.12874614  0.57322607 -0.5257471   0.57874835]]
[[ True False  True  True]
 [False  True  True  True]
 [ True  True  True False]
 [ True  True False  True]]
[[ 1 -1  1  1]
 [-1  1  1  1]
 [ 1  1  1 -1]
 [ 1  1 -1  1]]
